import streamlit as st
import base64
import os
from io import BytesIO

# Import local modules
from src.models.llama_model import LlamaModel
from src.chains.chemical_extractor import ChemicalExtractor
from src.services.smiles_lookup import SMILESLookup
from src.services.molecule_renderer import MoleculeRenderer
from src.utils.logging_utils import setup_logger
from config.settings import APP_TITLE, APP_DESCRIPTION, MODEL_PATH

# Setup logging
logger = setup_logger(__name__)

def load_css():
    """Load custom CSS"""
    with open(os.path.join("static", "css", "style.css")) as f:
        st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)

def get_chemical_description(chemical_name, extractor):
    """
    Get a brief 1-2 sentence description of a chemical compound using LLM.
    
    Args:
        chemical_name (str): Name of the chemical
        extractor: ChemicalExtractor instance with LLM
        
    Returns:
        str: Brief description of the chemical
    """
    try:
        # Create a prompt for generating a short description
        description_prompt = f"""
You are a chemistry expert. Provide a brief 1-2 sentence description of {chemical_name}.
Include its chemical formula if known, and mention its main properties or uses.
Keep it concise and informative.

Chemical: {chemical_name}

Description:
"""
        
        # Generate description using the LLM
        logger.info(f"Generating description for {chemical_name} using LLM")
        description = extractor.llm.generate(description_prompt)
        
        # Clean up the response
        description = description.strip()
        
        # If the response is too long, truncate to first 2 sentences
        sentences = description.split('.')
        if len(sentences) > 2:
            description = '. '.join(sentences[:2]) + '.'
            
        logger.info(f"Generated description for {chemical_name}: {description[:100]}...")
        return description
        
    except Exception as e:
        logger.error(f"Error generating description for {chemical_name}: {str(e)}")
        # Fallback to generic message if LLM fails
        return "This chemical is commonly used in research and industrial applications."

def main():
    # Load the model and initialize components
    @st.cache_resource
    def load_model():
        logger.info("Loading LLaMA model...")
        model = LlamaModel()
        return model
    
    @st.cache_resource
    def init_components(_model):
        # Using leading underscore to tell Streamlit not to hash this argument
        extractor = ChemicalExtractor(_model)
        smiles_lookup = SMILESLookup()
        renderer = MoleculeRenderer()
        return extractor, smiles_lookup, renderer
    
    # Page configuration
    st.set_page_config(
        page_title=APP_TITLE,
        page_icon="🧪",
        layout="wide"
    )
    
    # Load custom CSS
    load_css()
    
    # App header
    st.title(APP_TITLE)
    st.markdown(APP_DESCRIPTION)
    
    # Initialize model and components
    with st.spinner("Loading model and components..."):
        model = load_model()
        extractor, smiles_lookup, renderer = init_components(model)
    
    # User input
    user_query = st.text_input("Enter your chemical query:", placeholder="What is benzene?")
    
    if user_query:
        with st.spinner("Processing your query..."):
            # Log the query for debugging
            logger.info(f"Processing query: {user_query}")
            
            try:
                # Extract chemical name from query
                chemical_name = extractor.extract_chemical_name(user_query)
                
                if chemical_name:
                    st.success(f"Detected chemical: {chemical_name}")
                    
                    # Show chemical description immediately (generated by LLM)
                    with st.spinner("Generating description..."):
                        description = get_chemical_description(chemical_name, extractor)
                    st.info(f"**About {chemical_name}:** {description}")
                    
                    # Look up SMILES
                    try:
                        smiles = smiles_lookup.get_smiles(chemical_name)
                        st.info(f"SMILES: {smiles}")
                        
                        # Render molecule
                        if smiles:
                            img = renderer.render_molecule(smiles)
                            if img:
                                st.image(img, caption=f"Structure of {chemical_name}")
                    except Exception as e:
                        st.error(f"Error looking up chemical: {str(e)}")
                        logger.error(f"SMILES lookup error: {str(e)}")
                else:
                    st.warning("No specific chemical detected in your query. Please try again with a different query.")
                    logger.warning(f"No chemical detected in query: {user_query}")
            except Exception as e:
                st.error(f"Error processing query: {str(e)}")
                logger.error(f"Query processing error: {str(e)}", exc_info=True)
    
    # Additional information
    with st.expander("About this app"):
        st.markdown("""
        This app uses a local LLaMA model to extract chemical names from natural language queries,
        then fetches their SMILES representation from OPSIN, and renders the molecular structure.
        """)
        
    # Debug section
    if st.checkbox("Show debug information", False):
        st.subheader("Debug Information")
        st.write("This section is for troubleshooting the app.")
        
        with st.expander("Test chemical extraction"):
            test_query = st.text_input("Test query:", "What is benzene?")
            if st.button("Test extraction"):
                st.write(f"Testing extraction for: '{test_query}'")
                try:
                    # Use the LLM-based extraction
                    result = extractor.extract_chemical_name(test_query)
                    
                    if result:
                        st.success(f"Extracted chemical: {result}")
                    else:
                        st.warning("No chemical detected in the query")
                    
                except Exception as e:
                    st.error(f"Error during test: {str(e)}")

if __name__ == "__main__":
    main()
